# Generated by Django 4.2.16 on 2024-10-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='like',
            table='Like',
        ),
        # migrations.AlterModelTable(
        #     name = "post",
        #     table = "post_table"
        # )
    ]
