# Generated by Django 4.2.16 on 2024-11-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post_app", "0003_comment_deleted_at_comment_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="like",
            name="updated_at",
        ),
    ]
