# Generated by Django 4.2.16 on 2024-10-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_alter_comment_table_alter_like_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
    ]
