# Generated by Django 4.2.16 on 2024-11-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post_app", "0004_remove_like_created_at_remove_like_updated_at"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comment",
            table="comment",
        ),
        migrations.AlterModelTable(
            name="like",
            table="like",
        ),
        migrations.AlterModelTable(
            name="post",
            table="post",
        ),
    ]
