# Generated by Django 4.2.16 on 2024-11-12 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post_app", "0004_savedpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_posts",
                to="post_app.post",
            ),
        ),
        migrations.AlterField(
            model_name="savedpost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
