# Generated by Django 4.2.16 on 2024-11-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="friendrequest",
            table="friend_request",
        ),
        migrations.AlterModelTable(
            name="friendship",
            table="friendship",
        ),
        migrations.AlterModelTable(
            name="otpverification",
            table="user_otp",
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
