# Generated by Django 4.2.16 on 2024-10-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.BigIntegerField(default=+91),
            preserve_default=False,
        ),
    ]
