# Generated by Django 4.2.16 on 2024-11-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_is_private_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="accepted",
                max_length=10,
            ),
        ),
    ]
