# Generated by Django 4.2.16 on 2024-10-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country_code',
        ),
    ]
