# Generated by Django 4.2.16 on 2024-11-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_follow_status"),
    ]

    operations = []
