# Generated by Django 4.2.16 on 2024-11-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
