# Generated by Django 4.2.16 on 2024-10-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_bio_user_links_user_other_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username_change_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
