# Generated by Django 4.2.16 on 2024-11-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_user_last_username_change_user_username_change_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
