# Generated by Django 4.2.16 on 2024-11-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_freindrequest_freindship_delete_blacklistedtoken"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FreindRequest",
            new_name="FriendRequest",
        ),
        migrations.RenameModel(
            old_name="Freindship",
            new_name="Friendship",
        ),
    ]
