# Generated by Django 4.2.16 on 2024-11-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_follow_unique_together_follow_following_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="accepted",
                max_length=10,
            ),
        ),
    ]
