# Generated by Django 4.2.16 on 2024-11-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_rename_freindrequest_friendrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
