# Generated by Django 4.2.16 on 2024-11-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_base"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Base",
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="friendship",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="otpverification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
