# Generated by Django 4.2.16 on 2024-11-16 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_follow_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                related_name="following_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
