# Generated by Django 4.2.16 on 2024-11-18 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_remove_user_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a1246df6-0bae-4497-8248-49f89e017b26"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
